title: Khalil Anderson
logo: KhalilHeadshotSmall.jpg
description: 4th year       Northwestern Unviersity     CS PhD Candidate      Artificial Intelligence
show_downloads: false
theme: jekyll-theme-minimal
